RATE = .55 # voice speed
VOICE_PREFERENCES = ['Martha', 'Arthur', 'Martin']

# Available Voices, Okt 2024
'''
    {'name': 'Majed', 'language': 'ar-001', 'identifier': 'com.apple.voice.compact.ar-001.Maged'}
    {'name': 'Daria', 'language': 'bg-BG', 'identifier': 'com.apple.voice.compact.bg-BG.Daria'}
    {'name': 'Montse', 'language': 'ca-ES', 'identifier': 'com.apple.voice.compact.ca-ES.Montserrat'}
    {'name': 'Zuzana', 'language': 'cs-CZ', 'identifier': 'com.apple.voice.compact.cs-CZ.Zuzana'}
    {'name': 'Sara', 'language': 'da-DK', 'identifier': 'com.apple.voice.compact.da-DK.Sara'}
    {'name': 'Sandy', 'language': 'de-DE', 'identifier': 'com.apple.eloquence.de-DE.Sandy'}
    {'name': 'Shelley', 'language': 'de-DE', 'identifier': 'com.apple.eloquence.de-DE.Shelley'}
    {'name': 'Helena', 'language': 'de-DE', 'identifier': 'com.apple.ttsbundle.siri_Helena_de-DE_compact'}
    {'name': 'Grandma', 'language': 'de-DE', 'identifier': 'com.apple.eloquence.de-DE.Grandma'}
    {'name': 'Grandpa', 'language': 'de-DE', 'identifier': 'com.apple.eloquence.de-DE.Grandpa'}
    {'name': 'Eddy', 'language': 'de-DE', 'identifier': 'com.apple.eloquence.de-DE.Eddy'}
    {'name': 'Reed', 'language': 'de-DE', 'identifier': 'com.apple.eloquence.de-DE.Reed'}
    {'name': 'Anna', 'language': 'de-DE', 'identifier': 'com.apple.voice.compact.de-DE.Anna'}
    {'name': 'Martin', 'language': 'de-DE', 'identifier': 'com.apple.ttsbundle.siri_Martin_de-DE_compact'}
    {'name': 'Rocko', 'language': 'de-DE', 'identifier': 'com.apple.eloquence.de-DE.Rocko'}
    {'name': 'Flo', 'language': 'de-DE', 'identifier': 'com.apple.eloquence.de-DE.Flo'}
    {'name': 'Melina', 'language': 'el-GR', 'identifier': 'com.apple.voice.compact.el-GR.Melina'}
    {'name': 'Gordon', 'language': 'en-AU', 'identifier': 'com.apple.ttsbundle.siri_Gordon_en-AU_compact'}
    {'name': 'Karen', 'language': 'en-AU', 'identifier': 'com.apple.voice.compact.en-AU.Karen'}
    {'name': 'Catherine', 'language': 'en-AU', 'identifier': 'com.apple.ttsbundle.siri_Catherine_en-AU_compact'}
    {'name': 'Rocko', 'language': 'en-GB', 'identifier': 'com.apple.eloquence.en-GB.Rocko'}
    {'name': 'Shelley', 'language': 'en-GB', 'identifier': 'com.apple.eloquence.en-GB.Shelley'}
    {'name': 'Daniel', 'language': 'en-GB', 'identifier': 'com.apple.voice.compact.en-GB.Daniel'}
    {'name': 'Martha', 'language': 'en-GB', 'identifier': 'com.apple.ttsbundle.siri_Martha_en-GB_compact'}
    {'name': 'Grandma', 'language': 'en-GB', 'identifier': 'com.apple.eloquence.en-GB.Grandma'}
    {'name': 'Grandpa', 'language': 'en-GB', 'identifier': 'com.apple.eloquence.en-GB.Grandpa'}
    {'name': 'Flo', 'language': 'en-GB', 'identifier': 'com.apple.eloquence.en-GB.Flo'}
    {'name': 'Eddy', 'language': 'en-GB', 'identifier': 'com.apple.eloquence.en-GB.Eddy'}
    {'name': 'Reed', 'language': 'en-GB', 'identifier': 'com.apple.eloquence.en-GB.Reed'}
    {'name': 'Sandy', 'language': 'en-GB', 'identifier': 'com.apple.eloquence.en-GB.Sandy'}
    {'name': 'Arthur', 'language': 'en-GB', 'identifier': 'com.apple.ttsbundle.siri_Arthur_en-GB_compact'}
    {'name': 'Moira', 'language': 'en-IE', 'identifier': 'com.apple.voice.compact.en-IE.Moira'}
    {'name': 'Rishi', 'language': 'en-IN', 'identifier': 'com.apple.voice.compact.en-IN.Rishi'}
    {'name': 'Flo', 'language': 'en-US', 'identifier': 'com.apple.eloquence.en-US.Flo'}
    {'name': 'Bahh', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Bahh'}
    {'name': 'Albert', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Albert'}
    {'name': 'Fred', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Fred'}
    {'name': 'Jester', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Hysterical'}
    {'name': 'Organ', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Organ'}
    {'name': 'Cellos', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Cellos'}
    {'name': 'Zarvox', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Zarvox'}
    {'name': 'Rocko', 'language': 'en-US', 'identifier': 'com.apple.eloquence.en-US.Rocko'}
    {'name': 'Shelley', 'language': 'en-US', 'identifier': 'com.apple.eloquence.en-US.Shelley'}
    {'name': 'Superstar', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Princess'}
    {'name': 'Grandma', 'language': 'en-US', 'identifier': 'com.apple.eloquence.en-US.Grandma'}
    {'name': 'Eddy', 'language': 'en-US', 'identifier': 'com.apple.eloquence.en-US.Eddy'}
    {'name': 'Bells', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Bells'}
    {'name': 'Grandpa', 'language': 'en-US', 'identifier': 'com.apple.eloquence.en-US.Grandpa'}
    {'name': 'Trinoids', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Trinoids'}
    {'name': 'Kathy', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Kathy'}
    {'name': 'Reed', 'language': 'en-US', 'identifier': 'com.apple.eloquence.en-US.Reed'}
    {'name': 'Boing', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Boing'}
    {'name': 'Whisper', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Whisper'}
    {'name': 'Wobble', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Deranged'}
    {'name': 'Good News', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.GoodNews'}
    {'name': 'Nicky', 'language': 'en-US', 'identifier': 'com.apple.ttsbundle.siri_Nicky_en-US_compact'}
    {'name': 'Bad News', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.BadNews'}
    {'name': 'Aaron', 'language': 'en-US', 'identifier': 'com.apple.ttsbundle.siri_Aaron_en-US_compact'}
    {'name': 'Bubbles', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Bubbles'}
    {'name': 'Samantha', 'language': 'en-US', 'identifier': 'com.apple.voice.compact.en-US.Samantha'}
    {'name': 'Sandy', 'language': 'en-US', 'identifier': 'com.apple.eloquence.en-US.Sandy'}
    {'name': 'Junior', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Junior'}
    {'name': 'Ralph', 'language': 'en-US', 'identifier': 'com.apple.speech.synthesis.voice.Ralph'}
    {'name': 'Tessa', 'language': 'en-ZA', 'identifier': 'com.apple.voice.compact.en-ZA.Tessa'}
    {'name': 'Shelley', 'language': 'es-ES', 'identifier': 'com.apple.eloquence.es-ES.Shelley'}
    {'name': 'Grandma', 'language': 'es-ES', 'identifier': 'com.apple.eloquence.es-ES.Grandma'}
    {'name': 'Rocko', 'language': 'es-ES', 'identifier': 'com.apple.eloquence.es-ES.Rocko'}
    {'name': 'Grandpa', 'language': 'es-ES', 'identifier': 'com.apple.eloquence.es-ES.Grandpa'}
    {'name': 'Mónica', 'language': 'es-ES', 'identifier': 'com.apple.voice.compact.es-ES.Monica'}
    {'name': 'Sandy', 'language': 'es-ES', 'identifier': 'com.apple.eloquence.es-ES.Sandy'}
    {'name': 'Flo', 'language': 'es-ES', 'identifier': 'com.apple.eloquence.es-ES.Flo'}
    {'name': 'Eddy', 'language': 'es-ES', 'identifier': 'com.apple.eloquence.es-ES.Eddy'}
    {'name': 'Reed', 'language': 'es-ES', 'identifier': 'com.apple.eloquence.es-ES.Reed'}
    {'name': 'Rocko', 'language': 'es-MX', 'identifier': 'com.apple.eloquence.es-MX.Rocko'}
    {'name': 'Paulina', 'language': 'es-MX', 'identifier': 'com.apple.voice.compact.es-MX.Paulina'}
    {'name': 'Flo', 'language': 'es-MX', 'identifier': 'com.apple.eloquence.es-MX.Flo'}
    {'name': 'Sandy', 'language': 'es-MX', 'identifier': 'com.apple.eloquence.es-MX.Sandy'}
    {'name': 'Eddy', 'language': 'es-MX', 'identifier': 'com.apple.eloquence.es-MX.Eddy'}
    {'name': 'Shelley', 'language': 'es-MX', 'identifier': 'com.apple.eloquence.es-MX.Shelley'}
    {'name': 'Grandma', 'language': 'es-MX', 'identifier': 'com.apple.eloquence.es-MX.Grandma'}
    {'name': 'Reed', 'language': 'es-MX', 'identifier': 'com.apple.eloquence.es-MX.Reed'}
    {'name': 'Grandpa', 'language': 'es-MX', 'identifier': 'com.apple.eloquence.es-MX.Grandpa'}
    {'name': 'Shelley', 'language': 'fi-FI', 'identifier': 'com.apple.eloquence.fi-FI.Shelley'}
    {'name': 'Grandma', 'language': 'fi-FI', 'identifier': 'com.apple.eloquence.fi-FI.Grandma'}
    {'name': 'Grandpa', 'language': 'fi-FI', 'identifier': 'com.apple.eloquence.fi-FI.Grandpa'}
    {'name': 'Sandy', 'language': 'fi-FI', 'identifier': 'com.apple.eloquence.fi-FI.Sandy'}
    {'name': 'Satu', 'language': 'fi-FI', 'identifier': 'com.apple.voice.compact.fi-FI.Satu'}
    {'name': 'Eddy', 'language': 'fi-FI', 'identifier': 'com.apple.eloquence.fi-FI.Eddy'}
    {'name': 'Rocko', 'language': 'fi-FI', 'identifier': 'com.apple.eloquence.fi-FI.Rocko'}
    {'name': 'Reed', 'language': 'fi-FI', 'identifier': 'com.apple.eloquence.fi-FI.Reed'}
    {'name': 'Flo', 'language': 'fi-FI', 'identifier': 'com.apple.eloquence.fi-FI.Flo'}
    {'name': 'Shelley', 'language': 'fr-CA', 'identifier': 'com.apple.eloquence.fr-CA.Shelley'}
    {'name': 'Grandma', 'language': 'fr-CA', 'identifier': 'com.apple.eloquence.fr-CA.Grandma'}
    {'name': 'Grandpa', 'language': 'fr-CA', 'identifier': 'com.apple.eloquence.fr-CA.Grandpa'}
    {'name': 'Rocko', 'language': 'fr-CA', 'identifier': 'com.apple.eloquence.fr-CA.Rocko'}
    {'name': 'Eddy', 'language': 'fr-CA', 'identifier': 'com.apple.eloquence.fr-CA.Eddy'}
    {'name': 'Reed', 'language': 'fr-CA', 'identifier': 'com.apple.eloquence.fr-CA.Reed'}
    {'name': 'Amélie', 'language': 'fr-CA', 'identifier': 'com.apple.voice.compact.fr-CA.Amelie'}
    {'name': 'Flo', 'language': 'fr-CA', 'identifier': 'com.apple.eloquence.fr-CA.Flo'}
    {'name': 'Sandy', 'language': 'fr-CA', 'identifier': 'com.apple.eloquence.fr-CA.Sandy'}
    {'name': 'Grandma', 'language': 'fr-FR', 'identifier': 'com.apple.eloquence.fr-FR.Grandma'}
    {'name': 'Flo', 'language': 'fr-FR', 'identifier': 'com.apple.eloquence.fr-FR.Flo'}
    {'name': 'Rocko', 'language': 'fr-FR', 'identifier': 'com.apple.eloquence.fr-FR.Rocko'}
    {'name': 'Grandpa', 'language': 'fr-FR', 'identifier': 'com.apple.eloquence.fr-FR.Grandpa'}
    {'name': 'Sandy', 'language': 'fr-FR', 'identifier': 'com.apple.eloquence.fr-FR.Sandy'}
    {'name': 'Eddy', 'language': 'fr-FR', 'identifier': 'com.apple.eloquence.fr-FR.Eddy'}
    {'name': 'Daniel', 'language': 'fr-FR', 'identifier': 'com.apple.ttsbundle.siri_Daniel_fr-FR_compact'}
    {'name': 'Thomas', 'language': 'fr-FR', 'identifier': 'com.apple.voice.compact.fr-FR.Thomas'}
    {'name': 'Jacques', 'language': 'fr-FR', 'identifier': 'com.apple.eloquence.fr-FR.Jacques'}
    {'name': 'Marie', 'language': 'fr-FR', 'identifier': 'com.apple.ttsbundle.siri_Marie_fr-FR_compact'}
    {'name': 'Shelley', 'language': 'fr-FR', 'identifier': 'com.apple.eloquence.fr-FR.Shelley'}
    {'name': 'Carmit', 'language': 'he-IL', 'identifier': 'com.apple.voice.compact.he-IL.Carmit'}
    {'name': 'Lekha', 'language': 'hi-IN', 'identifier': 'com.apple.voice.compact.hi-IN.Lekha'}
    {'name': 'Lana', 'language': 'hr-HR', 'identifier': 'com.apple.voice.compact.hr-HR.Lana'}
    {'name': 'Tünde', 'language': 'hu-HU', 'identifier': 'com.apple.voice.compact.hu-HU.Mariska'}
    {'name': 'Damayanti', 'language': 'id-ID', 'identifier': 'com.apple.voice.compact.id-ID.Damayanti'}
    {'name': 'Eddy', 'language': 'it-IT', 'identifier': 'com.apple.eloquence.it-IT.Eddy'}
    {'name': 'Sandy', 'language': 'it-IT', 'identifier': 'com.apple.eloquence.it-IT.Sandy'}
    {'name': 'Reed', 'language': 'it-IT', 'identifier': 'com.apple.eloquence.it-IT.Reed'}
    {'name': 'Shelley', 'language': 'it-IT', 'identifier': 'com.apple.eloquence.it-IT.Shelley'}
    {'name': 'Grandma', 'language': 'it-IT', 'identifier': 'com.apple.eloquence.it-IT.Grandma'}
    {'name': 'Grandpa', 'language': 'it-IT', 'identifier': 'com.apple.eloquence.it-IT.Grandpa'}
    {'name': 'Flo', 'language': 'it-IT', 'identifier': 'com.apple.eloquence.it-IT.Flo'}
    {'name': 'Rocko', 'language': 'it-IT', 'identifier': 'com.apple.eloquence.it-IT.Rocko'}
    {'name': 'Alice', 'language': 'it-IT', 'identifier': 'com.apple.voice.compact.it-IT.Alice'}
    {'name': 'O-ren', 'language': 'ja-JP', 'identifier': 'com.apple.ttsbundle.siri_O-ren_ja-JP_compact'}
    {'name': 'Kyoko', 'language': 'ja-JP', 'identifier': 'com.apple.voice.compact.ja-JP.Kyoko'}
    {'name': 'Hattori', 'language': 'ja-JP', 'identifier': 'com.apple.ttsbundle.siri_Hattori_ja-JP_compact'}
    {'name': 'Yuna', 'language': 'ko-KR', 'identifier': 'com.apple.voice.compact.ko-KR.Yuna'}
    {'name': 'Amira', 'language': 'ms-MY', 'identifier': 'com.apple.voice.compact.ms-MY.Amira'}
    {'name': 'Nora', 'language': 'nb-NO', 'identifier': 'com.apple.voice.compact.nb-NO.Nora'}
    {'name': 'Ellen', 'language': 'nl-BE', 'identifier': 'com.apple.voice.compact.nl-BE.Ellen'}
    {'name': 'Xander', 'language': 'nl-NL', 'identifier': 'com.apple.voice.compact.nl-NL.Xander'}
    {'name': 'Zosia', 'language': 'pl-PL', 'identifier': 'com.apple.voice.compact.pl-PL.Zosia'}
    {'name': 'Reed', 'language': 'pt-BR', 'identifier': 'com.apple.eloquence.pt-BR.Reed'}
    {'name': 'Luciana', 'language': 'pt-BR', 'identifier': 'com.apple.voice.compact.pt-BR.Luciana'}
    {'name': 'Shelley', 'language': 'pt-BR', 'identifier': 'com.apple.eloquence.pt-BR.Shelley'}
    {'name': 'Grandma', 'language': 'pt-BR', 'identifier': 'com.apple.eloquence.pt-BR.Grandma'}
    {'name': 'Grandpa', 'language': 'pt-BR', 'identifier': 'com.apple.eloquence.pt-BR.Grandpa'}
    {'name': 'Rocko', 'language': 'pt-BR', 'identifier': 'com.apple.eloquence.pt-BR.Rocko'}
    {'name': 'Flo', 'language': 'pt-BR', 'identifier': 'com.apple.eloquence.pt-BR.Flo'}
    {'name': 'Sandy', 'language': 'pt-BR', 'identifier': 'com.apple.eloquence.pt-BR.Sandy'}
    {'name': 'Eddy', 'language': 'pt-BR', 'identifier': 'com.apple.eloquence.pt-BR.Eddy'}
    {'name': 'Joana', 'language': 'pt-PT', 'identifier': 'com.apple.voice.compact.pt-PT.Joana'}
    {'name': 'Ioana', 'language': 'ro-RO', 'identifier': 'com.apple.voice.compact.ro-RO.Ioana'}
    {'name': 'Milena', 'language': 'ru-RU', 'identifier': 'com.apple.voice.compact.ru-RU.Milena'}
    {'name': 'Laura', 'language': 'sk-SK', 'identifier': 'com.apple.voice.compact.sk-SK.Laura'}
    {'name': 'Alva', 'language': 'sv-SE', 'identifier': 'com.apple.voice.compact.sv-SE.Alva'}
    {'name': 'Kanya', 'language': 'th-TH', 'identifier': 'com.apple.voice.compact.th-TH.Kanya'}
    {'name': 'Yelda', 'language': 'tr-TR', 'identifier': 'com.apple.voice.compact.tr-TR.Yelda'}
    {'name': 'Lesya', 'language': 'uk-UA', 'identifier': 'com.apple.voice.compact.uk-UA.Lesya'}
    {'name': 'Linh', 'language': 'vi-VN', 'identifier': 'com.apple.voice.compact.vi-VN.Linh'}
    {'name': 'Li-mu', 'language': 'zh-CN', 'identifier': 'com.apple.ttsbundle.siri_Li-mu_zh-CN_compact'}
    {'name': 'Tingting', 'language': 'zh-CN', 'identifier': 'com.apple.voice.compact.zh-CN.Tingting'}
    {'name': 'Yu-shu', 'language': 'zh-CN', 'identifier': 'com.apple.ttsbundle.siri_Yu-shu_zh-CN_compact'}
    {'name': 'Sinji', 'language': 'zh-HK', 'identifier': 'com.apple.voice.compact.zh-HK.Sinji'}
    {'name': 'Meijia', 'language': 'zh-TW', 'identifier': 'com.apple.voice.compact.zh-TW.Meijia'}
'''

